package miceandcats;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Paul et Bruno
 */
public class GameFrame extends javax.swing.JFrame {

    private static final ImageIcon IN = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/In.png");
    private static final ImageIcon OUT = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/OUT.png");
    private static final ImageIcon FLECHE = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/fleches.png");
    private static final ImageIcon TELIN = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/TELIN.png");
    private static final ImageIcon TELOUT = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/TELOUT.png");
    private static final ImageIcon CHIEN = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/CHIEN1.png");
    private static final ImageIcon SOURIS = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/SOURIS1.png");
    private static final ImageIcon CHAT = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/CHAT2.png");
    private static final ImageIcon HERBE = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/HERBE.png");
    private static final ImageIcon MUR = new ImageIcon("C:/Users/Paul/Documents/NetBeansProjects/MiceAndCats/src/miceandcats/img/MUR.png");
   
    JLabel[][] jboard;
    
    public GameFrame() {
        initComponents();
        
        jboard = new JLabel[6][8];
        
        for(int i=0;i<6;i++){
            for(int j=0;j<8;j++){
                jboard[i][j] = new JLabel(HERBE);
                panelLab.add(jboard[i][j]); 
                
                jboard[i][j].addMouseListener(
                        new ControlFleche(i,j));
            }
        }
        jboard[0][0].setIcon(IN);
        jboard[5][7].setIcon(OUT);
        jboard[0][3].setIcon(MUR);
        jboard[1][1].setIcon(MUR);
        jboard[1][5].setIcon(MUR);
        jboard[2][3].setIcon(MUR);
        jboard[2][5].setIcon(MUR);
        jboard[2][6].setIcon(MUR);
        jboard[3][2].setIcon(MUR);
        jboard[4][3].setIcon(MUR);
        jboard[4][4].setIcon(MUR);
        jboard[4][6].setIcon(MUR);
        jboard[5][1].setIcon(MUR);
        jboard[3][1].setIcon(CHAT);
        jboard[3][4].setIcon(CHAT);
        jboard[5][5].setIcon(CHIEN);
        jboard[5][6].setIcon(CHIEN);
        jboard[3][6].setIcon(TELIN);
        jboard[4][0].setIcon(TELOUT);
        this.pack();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelH = new javax.swing.JPanel();
        panelLab = new javax.swing.JPanel();
        panelB = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblFleches = new javax.swing.JLabel();
        lblSouris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelH.setBackground(new java.awt.Color(0, 0, 0));

        panelLab.setBackground(new java.awt.Color(0, 0, 0));
        panelLab.setPreferredSize(new java.awt.Dimension(400, 300));
        panelLab.setLayout(new java.awt.GridLayout(6, 8));

        javax.swing.GroupLayout panelHLayout = new javax.swing.GroupLayout(panelH);
        panelH.setLayout(panelHLayout);
        panelHLayout.setHorizontalGroup(
            panelHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelHLayout.setVerticalGroup(
            panelHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(panelLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        btnNew.setText("Commencer la partie");

        btnReset.setText("Réinitialiser partie");

        lblFleches.setText("flèches restantes");

        lblSouris.setText("souris sauvés");

        javax.swing.GroupLayout panelBLayout = new javax.swing.GroupLayout(panelB);
        panelB.setLayout(panelBLayout);
        panelBLayout.setHorizontalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblSouris))
                    .addComponent(lblFleches))
                .addGap(199, 199, 199))
        );
        panelBLayout.setVerticalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFleches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSouris)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblFleches;
    private javax.swing.JLabel lblSouris;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel panelH;
    private javax.swing.JPanel panelLab;
    // End of variables declaration//GEN-END:variables

    public JLabel[][] getJboard() {
        return jboard;
    }

    public javax.swing.JButton getBtnNew() {
        return btnNew;
    }

    public javax.swing.JButton getBtnReset() {
        return btnReset;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.lblFleches = jLabel1;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.lblSouris = jLabel2;
    }
    
    public static ImageIcon getIN() {
        return IN;
    }

    public static ImageIcon getOUT() {
        return OUT;
    }

    public static ImageIcon getFLECHE() {
        return FLECHE;
    }

    public static ImageIcon getTELIN() {
        return TELIN;
    }

    public static ImageIcon getTELOUT() {
        return TELOUT;
    }

    public static ImageIcon getCHIEN() {
        return CHIEN;
    }

    public static ImageIcon getSOURIS() {
        return SOURIS;
    }

    public static ImageIcon getCHAT() {
        return CHAT;
    }

    public static ImageIcon getHERBE() {
        return HERBE;
    }
}
